/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.austral.ing.lab1;

import org.austral.ing.lab1.model.User;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import java.util.List;

public class UserRepositoryTest {

    private EntityManagerFactory sessionFactory;

    @Before
    public void setUp() {
        sessionFactory = Persistence.createEntityManagerFactory("lab1");
    }

    @After
    public void close() {
        sessionFactory.close();
    }

    @Test
    public void persistAUser() {
        final EntityManager entityManager = sessionFactory.createEntityManager();
        entityManager.getTransaction().begin();

        final User luke = User.create("luke.skywalker@jedis.org").firstName("Luke").lastName("Skywalker").build();
        final User leia = User.create("leia.skywalker@jedis.org").firstName("Leia").lastName("Skywalker").build();

        entityManager.persist(luke);
        entityManager.persist(leia);

        final List<User> users = entityManager.createQuery("SELECT u FROM User u WHERE u.email LIKE :email", User.class)
                .setParameter("email", "luke.skywalker@jedis.org").getResultList();

        final User anotherLuke = entityManager.find(User.class, luke.getId());

        entityManager.remove(leia);

        final List<User> allUsers = entityManager.createQuery("SELECT u FROM User u", User.class).getResultList();

        entityManager.getTransaction().commit();

        entityManager.close();
    }
}
